SELECT * FROM Funcionarios

CREATE TABLE DEPENDENTES (
	ID INT PRIMARY KEY, 
	NOME VARCHAR(200), 
	IDADE INT, 
	IDFUNCIONARIO INT
);

SELECT * FROM Funcionarios

ALTER TABLE FUNCIONARIOS ADD IDADE INT;

INSERT INTO Funcionarios VALUES (5, 'JOÃO', 40);
INSERT INTO Funcionarios VALUES (6, 'ROBERTO', 19);
INSERT INTO Funcionarios VALUES (7, 'MARIA', 50);

SELECT * FROM DEPENDENTES

INSERT INTO DEPENDENTES VALUES (1, 'AMANDA', 4, 5)
INSERT INTO DEPENDENTES VALUES (2, 'PEDRO', 1, 7)
INSERT INTO DEPENDENTES VALUES (3, 'ENZO', 19, 7)
INSERT INTO DEPENDENTES VALUES (4, 'AMANDA', 15, 7)


--CÓDIGO ORINÁRIO DA RESPOSTA DA PRÁTICA 2 ONDE PROJETOS FOI SUBSTITUÍDO POR DEPENENTES
SELECT Funcionarios.Nome, DEPENDENTES.NOME, DEPENDENTES.IDADE
FROM Funcionarios
INNER JOIN DEPENDENTES ON Funcionarios.FuncionarioID = DEPENDENTES.IDFUNCIONARIO;

--CÓDIGO ORINÁRIO DA RESPOSTA DA PRÁTICA 2 ONDE PROJETOS FOI SUBSTITUÍDO POR DEPENENTES
SELECT Funcionarios.Nome, DEPENDENTES.NOME, DEPENDENTES.IDADE
FROM Funcionarios
LEFT JOIN DEPENDENTES ON Funcionarios.FuncionarioID = DEPENDENTES.IDFUNCIONARIO;

--CÓDIGO ORINÁRIO DA RESPOSTA DA PRÁTICA 2 ONDE PROJETOS FOI SUBSTITUÍDO POR DEPENENTES
SELECT Funcionarios.Nome, DEPENDENTES.NOME, DEPENDENTES.IDADE
FROM Funcionarios -- TABELA DE BASE
RIGHT JOIN DEPENDENTES ON Funcionarios.FuncionarioID = DEPENDENTES.IDFUNCIONARIO;

SELECT Funcionarios.Nome, DEPENDENTES.NOME, DEPENDENTES.IDADE
FROM DEPENDENTES --TABELA DE BASE 
LEFT JOIN Funcionarios ON  Funcionarios.FuncionarioID = DEPENDENTES.IDFUNCIONARIO;

SELECT * FROM DEPENDENTES

INSERT INTO DEPENDENTES VALUES (5, 'TESTE SEM VINCULO DE FUNCIONARIO', 70, NULL)


-- PARENTESES DO QUE NAO FAZER
CREATE TABLE TESTENAOFAZER (
	C000 INT PRIMARY KEY, 
	C001 VARCHAR(200), 
	C002 INT, 
	C003 INT
);


CREATE TABLE TESTENAOFAZERSEGUNDO (	
	C001 VARCHAR(200), 
	C002 INT, 
	C003 INT,
	C004 INT PRIMARY KEY
);

ALTER TABLE TESTENAOFAZERSEGUNDO ADD C005 INT;
ALTER TABLE TESTENAOFAZERSEGUNDO ADD C006 INT;
ALTER TABLE TESTENAOFAZERSEGUNDO ADD C007 INT;

SELECT * FROM TESTENAOFAZER

INSERT INTO TESTENAOFAZER VALUES (1, 'CONTEUDO DO VARCHAR', 1, 1);

SELECT * FROM TESTENAOFAZERSEGUNDO

-----------------FINAL DO QUE NAO FAZER