-- CRIA A TABELA DE PESSOAS SEM CHAVE (PK)
CREATE TABLE PESSOAS (
	ID INT,
	NOME VARCHAR(200),
	PAPEL VARCHAR(50),
	CPF VARCHAR(14)
);


--INSERE NA TABELA DE PESSOAS UM REGISTRO
INSERT 
	
	INTO PESSOAS (ID, NOME, PAPEL, CPF) 

	VALUES (1, 'LEONARDO', 'PROFESSOR', '123456');
	
	
--INSERE NA TABELA DE PESSOAS UM REGISTRO SEM A COLUNA CPF
INSERT 
	
	INTO PESSOAS (ID, NOME, PAPEL) 

	VALUES (1, 'JOÃO DA SILVA CHAVES', 'ALUNO');
	
	
--BUSCA TODOS OS REGISTROS 
SELECT * FROM PESSOAS

--COMANDOS PARA INSERIR AS PESSOAS NA TABELA DE PESSOAS
INSERT INTO PESSOAS (ID, NOME, PAPEL, CPF) VALUES (1, 'João da Silva', 'Aluno', 'x');
INSERT INTO PESSOAS (ID, NOME, PAPEL, CPF) VALUES (2, 'Maria', 'Aluno', 'y');
INSERT INTO PESSOAS (ID, NOME, PAPEL, CPF) VALUES (3, 'José', 'Aluno', 'z');
INSERT INTO PESSOAS (ID, NOME, PAPEL, CPF) VALUES (5, 'André', 'Aluno', 'c');
INSERT INTO PESSOAS (ID, NOME, PAPEL, CPF) VALUES (0, 'João', 'Professor', 'd');


UPDATE PESSOAS SET CPF = 'NOVO NOV CPF2' -- ATUALIZA TODOS OS REGISTROS
UPDATE PESSOAS SET ID = 7 WHERE ID = 0 
UPDATE PESSOAS SET NOME = 'João novo sobrenome' WHERE NOME = 'João'
UPDATE PESSOAS SET NOME = 'João Novo Novo Nome' WHERE ID = 7
UPDATE PESSOAS SET ID = 8 WHERE NOME = 'LEONARDO' AND PAPEL = 'Aluno' AND CPF = '212121'


--ATUALIZA MÚLTIPLOS CAMPOS COM MÚLTIPLOS WHERES
UPDATE PESSOAS 
SET 
	NOME = 'João da Silva via multiplos campos', CPF = '123.123.123-90', PAPEL = 'Professor' 
WHERE 
	ID = 1 AND NOME = 'João da Silva' AND CPF = 'x'


UPDATE PESSOAS SET PAPEL = 'ALTERADO-prof' WHERE ((ID = 2) OR (ID = 3) OR (ID = 8)) AND (CPF = 'NOVO NOV CPF2')

--DELETA OS REGISTROS DA TABELA. LEMBRAR DE COLOCAR O WHERE
DELETE FROM PESSOAS WHERE ID = 1 AND CPF = '123.123.123-90'


--DELETA A ESTRUTURA DA TABELA INTEIRA E SEUS DADOS
DROP TABLE PESSOAS


--CRIA A TABELA COM UMA CONSTRAINT DE PRIMARY KEY
CREATE TABLE PESSOAS (
	ID INT, --PRIMARY KEY (PK) VAI TORNAR O CAMPO ID CHAVE PRIMARIA
	NOME VARCHAR(200),
	PAPEL VARCHAR(50),
	CPF VARCHAR(14), 
	CONSTRAINT PK_PESSOAS PRIMARY KEY (ID)
);


SELECT * FROM PESSOAS WHERE PAPEL <> 'Professor' --and, or, = (igual) <> (diferente)

--Criar a tabela de papeis
CREATE TABLE PAPEIS(
	ID INT, 
	DESCRICAO VARCHAR(50),
	CONSTRAINT PK_PAPEIS PRIMARY KEY (ID)
)

INSERT INTO PAPEIS VALUES (1, 'Professor');
INSERT INTO PAPEIS VALUES (2, 'Monitor');
INSERT INTO PAPEIS VALUES (3, 'Aluno');


update pessoas set papel = 1 where papel = 'Professor'
update pessoas set papel = 3 where papel = 'Aluno'
update pessoas set papel = 2 where papel = 'Monitor'

UPDATE PESSOAS SET PAPEL = '12345678910211' WHERE ID = 6
UPDATE PESSOAS SET PAPEL = 2 WHERE ID = 6

--ADICIONA UM CAMPO NOVO NA TABELA EXISTENTE
ALTER TABLE PESSOAS ADD ENDERECO VARCHAR(200)


--ADICIONA O CAMPO IDPAPEL
ALTER TABLE PESSOAS ADD IDPAPEL INT

UPDATE PESSOAS SET IDPAPEL = 2 WHERE ID = 6


--ADICIONAR UMA CHAVE EXTRANGEIRA NA TABELA DE PESSOAS PARA O CAMPO IDPAPEL 
--NAO VAI PERMITIR QUE NA TABELA DE PESSOAS A COLUNA IDPAPEL TENHA UM VALOR QUE NÃO  
--ESTEJA PREVIAMENTE INFORMADO NA TABELA DE PAPEIS
ALTER TABLE PESSOAS ADD CONSTRAINT FK_PESSOAS_IDPAPEL FOREIGN KEY (IDPAPEL) REFERENCES PAPEIS(ID)


UPDATE PESSOAS SET IDPAPEL = 1 WHERE ID = 5

--TENTA ATUALIZAR COM ID QUE NAO EXISTE A TABELA DE PESSOAS
UPDATE PESSOAS SET IDPAPEL = 200 WHERE ID = 5

--INSERE NA TABELA DE PAPEIS O ID 200 QUE É O GERENTE FINANCEIRO
INSERT INTO PAPEIS (ID, DESCRICAO) VALUES (200, 'Gerente Financeiro')

--TROCA O PAPEL PARA GERENTE FINANCEIRO
UPDATE PESSOAS SET IDPAPEL = 200 WHERE ID = 5
