select * from clientes
ALTER TABLE CLIENTES ADD ENDERECO VARCHAR(300)

SELECT * FROM PEDIDOS

CREATE TABLE FORMASPAGAMENTO (
ID INT PRIMARY KEY, 
CATEGORIA INT, 
DESCRICAO VARCHAR(100)
);

ALTER TABLE PEDIDOS ADD IDFORMAPAGAMENTO INT


CREATE TABLE TRANSPORTADORA (
	ID INT PRIMARY KEY, 
	DESCRICAO VARCHAR(200)
);


CREATE TABLE PEDIDOSTRANSPORTE(
	ID INT PRIMARY KEY, 
	IDPEDIDO INT, 
	IDTRANSPORTADORA INT, 
	SITUACAO INT, 
	PREVISAO DATETIME, 
);

UPDATE CLIENTES SET ENDERECO = 'ENDERECO DO ' + NOME

SELECT * FROM CLIENTES

SELECT * FROM FORMASPAGAMENTO

INSERT INTO FORMASPAGAMENTO (ID, CATEGORIA, DESCRICAO) VALUES (1, 2, 'PIX');
INSERT INTO FORMASPAGAMENTO (ID, CATEGORIA, DESCRICAO) VALUES (2, 1, 'CARTÃO CRÉDITO - MASTERCAD');
INSERT INTO FORMASPAGAMENTO (ID, CATEGORIA, DESCRICAO) VALUES (3, 1, 'CARTÃO CRÉTIDO - VISA');
INSERT INTO FORMASPAGAMENTO (ID, CATEGORIA, DESCRICAO) VALUES (4, 2, 'DÉBITO');

SELECT * FROM PEDIDOS

UPDATE PEDIDOS SET IDFORMAPAGAMENTO = 1 WHERE ID = 100 --USAR ESSA PARA TESTE
UPDATE PEDIDOS SET IDFORMAPAGAMENTO = 2 WHERE ID = 11
UPDATE PEDIDOS SET IDFORMAPAGAMENTO = 3 WHERE ID = 10

SELECT * FROM TRANSPORTADORA

INSERT INTO TRANSPORTADORA VALUES (1, 'TRANS ALFA');
INSERT INTO TRANSPORTADORA VALUES (2, 'TRANS BETA');
INSERT INTO TRANSPORTADORA VALUES (3, 'TRANS GAMA');

SELECT * FROM PEDIDOSTRANSPORTE

ALTER TABLE PEDIDOSTRANSPORTE DROP COLUMN SITUACAO

ALTER TABLE PEDIDOSTRANSPORTE ADD DESCRICAOSITUACAO VARCHAR(100)

INSERT INTO PEDIDOSTRANSPORTE VALUES (1, 100, 3, '2024-11-30', 'EM ROTA DE ENTREGA')

SELECT * FROM FORMASPAGAMENTO

INSERT INTO FORMASPAGAMENTO VALUES (5, 2, 'BOLETO BANCÁRIO')

SELECT 
	PEDIDOS.ID AS IDPEDIDO, PEDIDOS.DATAPEDIDO, PEDIDOS.IDFORMAPAGAMENTO, PEDIDOS.IDCLIENTE
FROM PEDIDOS
WHERE ID = 100


SELECT 
	PEDIDOS.ID AS IDPEDIDO, PEDIDOS.DATAPEDIDO, PEDIDOS.IDFORMAPAGAMENTO, FORMASPAGAMENTO.DESCRICAO,
	PEDIDOS.IDCLIENTE
FROM PEDIDOS
INNER JOIN FORMASPAGAMENTO ON FORMASPAGAMENTO.ID = PEDIDOS.IDFORMAPAGAMENTO
WHERE PEDIDOS.ID = 100

SELECT * FROM PEDIDOSTRANSPORTE

--ATENÇÃO AO INNER JOIN.. QUANDO FIZERMOS O PEDIDO TEM UM BREVE MOMENTO 
--QUE O PEDIDO NAO FOI ENTREGUE PARA NINGUEM LEVAR
SELECT 
	PEDIDOS.ID AS IDPEDIDO, PEDIDOS.DATAPEDIDO, PEDIDOS.IDFORMAPAGAMENTO, FORMASPAGAMENTO.DESCRICAO,
	PEDIDOS.IDCLIENTE, PEDIDOSTRANSPORTE.PREVISAO, PEDIDOSTRANSPORTE.DESCRICAOSITUACAO
FROM PEDIDOS
INNER JOIN FORMASPAGAMENTO ON FORMASPAGAMENTO.ID = PEDIDOS.IDFORMAPAGAMENTO
INNER JOIN PEDIDOSTRANSPORTE ON PEDIDOSTRANSPORTE.IDPEDIDO = PEDIDOS.ID
WHERE PEDIDOS.ID = 100

--EXEMPLO COM O PEDIDO QUE FOI REALIZADO AGORA. NESTE INSTANTE
SELECT 
	PEDIDOS.ID AS IDPEDIDO, PEDIDOS.DATAPEDIDO, PEDIDOS.IDFORMAPAGAMENTO, FORMASPAGAMENTO.DESCRICAO,
	PEDIDOS.IDCLIENTE, PEDIDOSTRANSPORTE.PREVISAO, PEDIDOSTRANSPORTE.DESCRICAOSITUACAO
FROM PEDIDOS
INNER JOIN FORMASPAGAMENTO ON FORMASPAGAMENTO.ID = PEDIDOS.IDFORMAPAGAMENTO
INNER JOIN PEDIDOSTRANSPORTE ON PEDIDOSTRANSPORTE.IDPEDIDO = PEDIDOS.ID
WHERE PEDIDOS.ID = 100

SELECT * FROM PEDIDOS 
UPDATE PEDIDOS SET IDFORMAPAGAMENTO = 3 WHERE ID = 5

--TEMOS UM PROBLEMA AQUI: EU FIZ O PEDIDO, PAGUEI O PEDIDO E NAO APARECE NADA PRA MIM
SELECT 
	PEDIDOS.ID AS IDPEDIDO, PEDIDOS.DATAPEDIDO, PEDIDOS.IDFORMAPAGAMENTO, FORMASPAGAMENTO.DESCRICAO,
	PEDIDOS.IDCLIENTE, PEDIDOSTRANSPORTE.PREVISAO, PEDIDOSTRANSPORTE.DESCRICAOSITUACAO
FROM PEDIDOS
INNER JOIN FORMASPAGAMENTO ON FORMASPAGAMENTO.ID = PEDIDOS.IDFORMAPAGAMENTO
INNER JOIN PEDIDOSTRANSPORTE ON PEDIDOSTRANSPORTE.IDPEDIDO = PEDIDOS.ID --ESSE AQUI O PROBLEMA
WHERE PEDIDOS.ID = 5

SELECT * FROM PEDIDOSTRANSPORTE WHERE IDPEDIDO = 5

--AQUI JÁ RESOLVEU, PORQUE MUDOU O JOIN
--PROCURAR SEMPRE COMPREENDER A DEPENDÊNCIAS DAS ENTIDADES/TABELAS
--PARA MODELAR A CONSULTA
SELECT 
	PEDIDOS.ID AS IDPEDIDO, PEDIDOS.DATAPEDIDO, PEDIDOS.IDFORMAPAGAMENTO, FORMASPAGAMENTO.DESCRICAO,
	PEDIDOS.IDCLIENTE, PEDIDOSTRANSPORTE.PREVISAO, PEDIDOSTRANSPORTE.DESCRICAOSITUACAO
FROM PEDIDOS
INNER JOIN FORMASPAGAMENTO ON FORMASPAGAMENTO.ID = PEDIDOS.IDFORMAPAGAMENTO
LEFT JOIN PEDIDOSTRANSPORTE ON PEDIDOSTRANSPORTE.IDPEDIDO = PEDIDOS.ID --ESSE AQUI O PROBLEMA
WHERE PEDIDOS.ID = 5


SELECT * FROM PEDIDOS

UPDATE PEDIDOS SET IDFORMAPAGAMENTO = NULL WHERE ID = 5

--SE MANTER COM O INNER NO FORMASPAGAMENTO NAO VIRÁ NADA.
--RACIOCÍNIO: GOSTARIA DE EXIBIR O PEDIDO, HAVENDO OU NÃO A FORMA DE PAGAMENTO E/OU INFORMAÇÕES DO TRANSPORTE
SELECT 
	PEDIDOS.ID AS IDPEDIDO, PEDIDOS.DATAPEDIDO, PEDIDOS.IDFORMAPAGAMENTO, FORMASPAGAMENTO.DESCRICAO,
	PEDIDOS.IDCLIENTE, PEDIDOSTRANSPORTE.PREVISAO, PEDIDOSTRANSPORTE.DESCRICAOSITUACAO
FROM PEDIDOS
LEFT JOIN FORMASPAGAMENTO ON FORMASPAGAMENTO.ID = PEDIDOS.IDFORMAPAGAMENTO
LEFT JOIN PEDIDOSTRANSPORTE ON PEDIDOSTRANSPORTE.IDPEDIDO = PEDIDOS.ID --ESSE AQUI O PROBLEMA
WHERE PEDIDOS.ID = 5

UPDATE PEDIDOS SET IDFORMAPAGAMENTO = 3 WHERE ID = 5


