
SELECT 
PEDIDOS.ID IDDOPEDIDO, PEDIDOS.DATAPEDIDO, PEDIDOS.IDCLIENTE, CLIENTES.NOME NOMEDOCLIENTE
FROM PEDIDOS
INNER JOIN CLIENTES ON PEDIDOS.IDCLIENTE = CLIENTES.ID



SELECT 
	PEDIDOS.ID IDDOPEDIDO, PEDIDOS.IDCLIENTE, CLIENTES.NOME NOMEDOCLIENTE, PEDIDOS.DATAPEDIDO, 
	PEDIDOSITENS.IDPRODUTO, PEDIDOSITENS.QUANTIDADE
FROM PEDIDOS
INNER JOIN CLIENTES ON PEDIDOS.IDCLIENTE = CLIENTES.ID
INNER JOIN PEDIDOSITENS ON PEDIDOS.ID = PEDIDOSITENS.IDPEDIDO



SELECT 
	PEDIDOS.ID IDDOPEDIDO, PEDIDOS.IDCLIENTE, CLIENTES.NOME NOMEDOCLIENTE, PEDIDOS.DATAPEDIDO, 
	PEDIDOSITENS.IDPRODUTO, PEDIDOSITENS.QUANTIDADE
FROM PEDIDOS
INNER JOIN CLIENTES ON PEDIDOS.IDCLIENTE = CLIENTES.ID
INNER JOIN PEDIDOSITENS ON PEDIDOS.ID = PEDIDOSITENS.IDPEDIDO
ORDER BY IDPEDIDO, IDCLIENTE, IDPRODUTO


SELECT 
	PEDIDOS.ID IDDOPEDIDO, PEDIDOS.IDCLIENTE, CLIENTES.NOME NOMEDOCLIENTE, PEDIDOS.DATAPEDIDO, 
	PEDIDOSITENS.IDPRODUTO, PRODUTOS.DESCRICAO, PEDIDOSITENS.QUANTIDADE, PRODUTOS.PRECO 

FROM PEDIDOS
INNER JOIN CLIENTES ON PEDIDOS.IDCLIENTE = CLIENTES.ID
INNER JOIN PEDIDOSITENS ON PEDIDOS.ID = PEDIDOSITENS.IDPEDIDO
INNER JOIN PRODUTOS ON PEDIDOSITENS.IDPRODUTO = PRODUTOS.ID
ORDER BY IDPEDIDO, IDCLIENTE, IDPRODUTO



SELECT 
	PEDIDOS.ID IDDOPEDIDO, PEDIDOS.IDCLIENTE, CLIENTES.NOME NOMEDOCLIENTE, PEDIDOS.DATAPEDIDO, 
	PEDIDOSITENS.IDPRODUTO, PRODUTOS.DESCRICAO, PEDIDOSITENS.QUANTIDADE, PRODUTOS.PRECO ,
	PEDIDOSITENS.QUANTIDADE * PRODUTOS.PRECO AS TOTAL
FROM PEDIDOS
INNER JOIN CLIENTES ON PEDIDOS.IDCLIENTE = CLIENTES.ID
INNER JOIN PEDIDOSITENS ON PEDIDOS.ID = PEDIDOSITENS.IDPEDIDO
INNER JOIN PRODUTOS ON PEDIDOSITENS.IDPRODUTO = PRODUTOS.ID
ORDER BY IDPEDIDO, IDCLIENTE, IDPRODUTO








